FROM wazoplatform/wazo-provd

RUN apt-get update && apt-get install -y python3 python3-venv
RUN python3 -m venv /opt/venv3
# Activate virtual env
ENV PATH="/opt/venv3/bin:$PATH"

RUN pip3 install wheel
RUN pip3 install https://github.com/wazo-platform/wazo-confgend-client/archive/master.zip
