FROM wazoplatform/wazo-auth-cli

RUN true \
    && pip install \
      psycopg2==2.7.7 \
      https://github.com/wazo-platform/wazo-auth-keys/archive/master.zip \
    && mkdir -p /etc/wazo-auth-keys/conf.d \
    && mkdir -p /var/lib/wazo-auth-keys
