FROM wazoplatform/wazo-webhookd

RUN apt-get update && apt-get install -y netcat wget
RUN wget -q -O- https://github.com/wazo-platform/wazo-webhookd/archive/master.tar.gz | tar -xz -C /usr/src --transform s/-master//
