---
- hosts: all
  tasks:
    - name: clone wazo-asterisk-config
      command: "git clone https://github.com/wazo-platform/wazo-asterisk-config.git"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: clone wazo-auth-key
      command: "git clone https://github.com/wazo-platform/wazo-auth-keys.git"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: clone xivo-manage-db
      command: "git clone https://github.com/wazo-platform/xivo-manage-db.git"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Pull images
      command: "docker-compose pull"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        LOCAL_GIT_REPOS: "."

    - name: Build images
      command: "docker-compose build --pull"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        LOCAL_GIT_REPOS: "."

    - name: Launch docker-compose to test docker images
      command: "docker-compose up --detach"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        LOCAL_GIT_REPOS: "."

    - name: Verify everything is fine
      command: "./verify.sh"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        LOCAL_GIT_REPOS: "."
